### ISSUE TITLE
Oracle Migration Components Roadmap

### ISSUE THREAD

**Issue by AndreOlivier** [AndreOlivier/hello-world#12]
- [ ] Anton has the migration approach that I would need to incorporate into the business case
- [ ] Preffered approach is using GoldenGate
- [ ] BCX/Oracle to both provide input quotes
